name: Build Lacie Engine

permissions: write-all

on: workflow_dispatch

jobs:
  Build:
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Android
            os: ubuntu-latest
            setupCommand: sh ./setup/unix.sh
            buildArgs: "android -final -release"
            artifactName: AndroidBuil
            artifactPath: "export/*/android/bin/app/build/outputs/apk/*/*.apk"
            doCache: "YES"
            
          - name: Windows
            os: windows-latest
            setupCommand: .\"setup/windows.bat"
            buildArgs: "windows -release -final"
            artifactName: WindowsBuild
            artifactPath: export\release\windows\bin\*
            doCache: "YES"
            
          - name: iOS
            os: macos-15
            setupCommand: sh ./setup/unix.sh
            buildArgs: "ios -final -nosign -release"
            artifactName: iOSBuild
            artifactPath: "export/release/ios/build/Release-iphoneos/*.ipa"
            doCache: "YES"
    uses: ./.github/workflows/build.yml
    with:
        name: ${{ matrix.name }}
        os: ${{ matrix.os }}
        setupCommand: ${{ matrix.setupCommand }}
        buildArgs: ${{ matrix.buildArgs }}
        artifactName: ${{ matrix.artifactName }}
        artifactPath: ${{ matrix.artifactPath }}
        doCache: ${{ matrix.doCache }}
